apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-svc
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
  selector:
    app: mongo
  type: ClusterIP
