apiVersion: v1
kind: Service
metadata:
  labels:
    app: strapi
  name: strapi-svc
  namespace: default
spec:
  # clusterIP: 10.152.183.13
  ports:
  - name: strapi
    port: 1337
    protocol: TCP
  selector:
    app: strapi
  # type: ClusterIP
