apiVersion: v1
kind: Service
metadata:
  labels: # pods
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 32003
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
    # version: v1 # access using versin labels
  sessionAffinity: None
  type: LoadBalancer
